// vue-天禹+源哥项目/天禹vue_staging/13_src_github搜索_事件总线/components/Search.vue
<template>
	<section class="jumbotron">
		<h3 class="jumbotron-heading">Search Github Users</h3>
		<div>
			<input type="text" v-model="keyWord" placeholder="enter the name you search"/>&nbsp;
			<button @click="search">Search</button>
		</div>
	</section>
</template>

<script>
	import axios from 'axios'
	export default {
		name:'Search',
		data(){
			return {
				keyWord:''
			}
		},
		methods: {
			async search(){
				//请求之前通知List组件更新他的data
				this.$bus.$emit('get-list-data',{isFirst:false,isLoading:true})
				try {
					//发送请求
					const response = await axios.get('https://api.github.com/search/users',{params:{q:this.keyWord}})
					const {items} = response.data
					//请求成功后，通知List组件更新他的data
					this.$bus.$emit('get-list-data',{isLoading:false,users:items})
				} catch (error) {
					//请求失败后，通知List组件更新他的data
					this.$bus.$emit('get-list-data',{isLoading:false,users:[],errMsg:error.message})
				}
			}
		},
	}
</script>

<style>

</style>

// 天禹 React/2021版资料/源码/react_staging/05_src_github搜索案例_axios/components/Search/index.jsx
import React, { Component } from 'react'
import axios from 'axios'

export default class Search extends Component {

	search = ()=>{
		//获取用户的输入(连续解构赋值+重命名)
		const {keyWordElement:{value:keyWord}} = this
		//发送请求前通知App更新状态
		this.props.updateAppState({isFirst:false,isLoading:true})
		//发送网络请求
		axios.get(`/api1/search/users?q=${keyWord}`).then(
			response => {
				//请求成功后通知App更新状态
				this.props.updateAppState({isLoading:false,users:response.data.items})
			},
			error => {
				//请求失败后通知App更新状态
				this.props.updateAppState({isLoading:false,err:error.message})
			}
		)
	}

	render() {
		return (
			<section className="jumbotron">
				<h3 className="jumbotron-heading">搜索github用户</h3>
				<div>
					<input ref={c => this.keyWordElement = c} type="text" placeholder="输入关键词点击搜索"/>&nbsp;
					<button onClick={this.search}>搜索</button>
				</div>
			</section>
		)
	}
}
