// 天禹 React/2021版资料/源码/react_staging/03_src_TodoList案例/components/Footer/index.jsx
import React, { Component } from 'react'
import './index.css'

export default class Footer extends Component {

	//全选checkbox的回调
	handleCheckAll = (event)=>{
		this.props.checkAllTodo(event.target.checked)
	}

	//清除已完成任务的回调
	handleClearAllDone = ()=>{
		this.props.clearAllDone()
	}

	render() {
		const {todos} = this.props
		//已完成的个数
		const doneCount = todos.reduce((pre,todo)=> pre + (todo.done ? 1 : 0),0)
		//总数
		const total = todos.length
		return (
			<div className="todo-footer">
				<label>
					<input type="checkbox" onChange={this.handleCheckAll} checked={doneCount === total && total !== 0 ? true : false}/>
				</label>
				<span>
					<span>已完成{doneCount}</span> / 全部{total}
				</span>
				<button onClick={this.handleClearAllDone} className="btn btn-danger">清除已完成任务</button>
			</div>
		)
	}
}

// 天禹vue+源哥项目/天禹vue_staging/09_src_todoList_自定义事件/components/Footer.vue
<template>
	<div class="todo-footer">
		<label>
			<input type="checkbox" v-model="isAll"/>
		</label>
		<span>
			<span>已完成{{doneCount}}</span> / 全部{{total}}
		</span>
		<button class="btn btn-danger" @click="clearAllDone">清除已完成任务</button>
	</div>
</template>

<script>
	export default {
		name:'Footer',
		props:['todos','updateAll','clearAll'],
		computed:{
			doneCount(){
				return this.todos.reduce((pre,current)=> pre += current.done ? 1 : 0 ,0)
			},
			total(){
				return this.todos.length
			},
			isAll:{
				//使用计算属性的set实现全选
				set(flag){
					this.updateAll(flag)
				},
				get(){
					return this.doneCount === this.total && this.total>0
				}
			}
		},
		methods:{
			//使用方法去全选
			/* checkAll(event){
				console.log('@',event.target.checked)
				this.updateAll(event.target.checked)
			} */

			clearAllDone(){
				if(confirm('确定删除所有已完成的todo吗？')){
					this.clearAll()
				}
			}
		},
	}
</script>

<style scoped>
	/*footer*/
	.todo-footer {
		height: 40px;
		line-height: 40px;
		padding-left: 6px;
		margin-top: 5px;
	}

	.todo-footer label {
		display: inline-block;
		margin-right: 20px;
		cursor: pointer;
	}

	.todo-footer label input {
		position: relative;
		top: -1px;
		vertical-align: middle;
		margin-right: 5px;
	}

	.todo-footer button {
		float: right;
		margin-top: 5px;
	}
</style>
