// 天禹 React/2021版资料/源码/react_staging/07_src_github搜索案例_fetch/components/Search/index.jsx
import React, { Component } from 'react'
import PubSub from 'pubsub-js'
// import axios from 'axios'

export default class Search extends Component {

	search = async()=>{
		//获取用户的输入(连续解构赋值+重命名)
		const {keyWordElement:{value:keyWord}} = this
		//发送请求前通知List更新状态
		PubSub.publish('atguigu',{isFirst:false,isLoading:true})
		//#region 发送网络请求---使用axios发送
		/* axios.get(`/api1/search/users2?q=${keyWord}`).then(
			response => {
				//请求成功后通知List更新状态
				PubSub.publish('atguigu',{isLoading:false,users:response.data.items})
			},
			error => {
				//请求失败后通知App更新状态
				PubSub.publish('atguigu',{isLoading:false,err:error.message})
			}
		) */
		//#endregion
			
		//发送网络请求---使用fetch发送（未优化）
		/* fetch(`/api1/search/users2?q=${keyWord}`).then(
			response => {
				console.log('联系服务器成功了');
				return response.json()
			},
			error => {
				console.log('联系服务器失败了',error);
				return new Promise(()=>{})
			}
		).then(
			response => {console.log('获取数据成功了',response);},
			error => {console.log('获取数据失败了',error);}
		) */

		//发送网络请求---使用fetch发送（优化）
		try {
			const response= await fetch(`/api1/search/users2?q=${keyWord}`)
			const data = await response.json()
			console.log(data);
			PubSub.publish('atguigu',{isLoading:false,users:data.items})
		} catch (error) {
			console.log('请求出错',error);
			PubSub.publish('atguigu',{isLoading:false,err:error.message})
		}
	}

	render() {
		return (
			<section className="jumbotron">
				<h3 className="jumbotron-heading">搜索github用户</h3>
				<div>
					<input ref={c => this.keyWordElement = c} type="text" placeholder="输入关键词点击搜索"/>&nbsp;
					<button onClick={this.search}>搜索</button>
				</div>
			</section>
		)
	}
}

// vue-天禹+源哥项目/天禹vue_staging/15_src_github搜索案例_vue-resource/components/Search.vue
<template>
	<section class="jumbotron">
		<h3 class="jumbotron-heading">Search Github Users</h3>
		<div>
			<input type="text" v-model="keyWord" placeholder="enter the name you search"/>&nbsp;
			<button @click="search">Search</button>
		</div>
	</section>
</template>

<script>
	// import axios from 'axios'
	import PubSub from 'pubsub-js'

	export default {
		name:'Search',
		data(){
			return {
				keyWord:''
			}
		},
		methods: {
			async search(){
				//请求之前通知List组件更新他的data
				// this.$bus.$emit('get-list-data',{isFirst:false,isLoading:true})
				PubSub.publish('get-list-data', {isFirst:false,isLoading:true});
				try {
					//发送请求---使用vue-resource
					const response = await this.$http.get('https://api.github.com/search/users',{params:{q:this.keyWord}})
					const {items} = response.data
					//请求成功后，通知List组件更新他的data
					// this.$bus.$emit('get-list-data',{isLoading:false,users:items})
					PubSub.publish('get-list-data', {isLoading:false,users:items});

				} catch (error) {
					//请求失败后，通知List组件更新他的data
					// this.$bus.$emit('get-list-data',{isLoading:false,users:[],errMsg:error.message})
					PubSub.publish('get-list-data', {isLoading:false,users:[],errMsg:error.message});

				}
			}
		},
		mounted() {
			console.log('vc',this)
		},
	}
</script>

<style>

</style>
