// React-天禹/2021版资料/源码/react_staging/03_src_TodoList案例/components/Item/index.jsx
import React, { Component } from 'react'
import './index.css'

export default class Item extends Component {

	state = {mouse:false} //标识鼠标移入、移出

	//鼠标移入、移出的回调
	handleMouse = (flag)=>{
		return ()=>{
			this.setState({mouse:flag})
		}
	}

	//勾选、取消勾选某一个todo的回调
	handleCheck = (id)=>{
		return (event)=>{
			this.props.updateTodo(id,event.target.checked)
		}
	}

	//删除一个todo的回调
	handleDelete = (id)=>{
		if(window.confirm('确定删除吗？')){
			this.props.deleteTodo(id)
		}
	}


	render() {
		const {id,name,done} = this.props
		const {mouse} = this.state
		return (
			<li style={{backgroundColor:mouse ? '#ddd' : 'white'}} onMouseEnter={this.handleMouse(true)} onMouseLeave={this.handleMouse(false)}>
				<label>
					<input type="checkbox" checked={done} onChange={this.handleCheck(id)}/>
					<span>{name}</span>
				</label>
				<button onClick={()=> this.handleDelete(id) } className="btn btn-danger" style={{display:mouse?'block':'none'}}>删除</button>
			</li>
		)
	}
}

// 天禹vue+源哥项目/天禹vue_staging/04_src_todoList案例/components/Item.vue
<template>
	<li
		@mouseenter="isEnter = true"
		@mouseleave="isEnter = false"
		:class="{'high-ligth':isEnter}"
	>
		<label>
			<input type="checkbox" :checked="todo.done" @click="update(index,$event)"/>
			<span>{{todo.name}}</span>
		</label>
		<button 
			class="btn btn-danger" 
			:style="{display:isEnter ? 'block' : 'none'}"
			@click="deleteT(index)"
		>删除</button>
	</li>
</template>

<script>
	export default {
		name:'Item',
		props:['todo','updateTodo','index','deleteTodo'],
		data(){
			return {
				isEnter:false //标识鼠标是否移入
			}
		},
		methods:{
			//用id去更新
			/* update(id,event){
				//通知App去更新这个todo
				const {checked} = event.target
				this.updateTodo(id,checked)
			} */

			//用index去更新todo
			update(index,event){
				//通知App去更新这个todo
				const {checked} = event.target
				this.updateTodo(index,checked)
			},

			//用于index去删除一个todo
			deleteT(index){
				if(confirm('确定删除吗')){
					this.deleteTodo(index)
				}
			}
		}
	}
</script>

<style scoped>
	/*item*/
	li {
		list-style: none;
		height: 36px;
		line-height: 36px;
		padding: 0 5px;
		border-bottom: 1px solid #ddd;
	}

	li label {
		float: left;
		cursor: pointer;
	}

	li label li input {
		vertical-align: middle;
		margin-right: 6px;
		position: relative;
		top: -1px;
	}

	li button {
		float: right;
		display: none;
		margin-top: 3px;
	}

	li:before {
		content: initial;
	}

	li:last-child {
		border-bottom: none;
	}
	
	.high-ligth{
		background-color: #ddd;
	}
</style>
