// 天禹 React/2021版资料/源码/react_staging/04_src_配置代理/App.jsx
import React, { Component } from 'react'
import axios from 'axios'

export default class App extends Component {

	getStudentData = ()=>{
		axios.get('http://localhost:3000/api1/students').then(
			response => {console.log('成功了',response.data);},
			error => {console.log('失败了',error);}
		)
	}

	getCarData = ()=>{
		axios.get('http://localhost:3000/api2/cars').then(
			response => {console.log('成功了',response.data);},
			error => {console.log('失败了',error);}
		)
	}

	render() {
		return (
			<div>
				<button onClick={this.getStudentData}>点我获取学生数据</button>
				<button onClick={this.getCarData}>点我获取汽车数据</button>
			</div>
		)
	}
}

// 天禹vue+源哥项目/天禹vue_staging/30_src_配置代理/App.vue
<template>
	<div>	
		<button @click="getStuInfo">点我获取学生信息</button>
		<button @click="getCarInfo">点我获取汽车信息</button>
	</div>
</template>

<script>
	import axios from 'axios'
	export default {
		name:'App',
		methods:{
			getStuInfo(){
				axios.get('/api1/students').then(
					response => {console.log('请求成功了',response.data)},
					error => {console.log('请求失败了',error.message)}
				)
			},
			getCarInfo(){
				axios.get('api2/cars').then(
					response => {console.log('请求成功了',response.data)},
					error => {console.log('请求失败了',error.message)}
				)
			}
		}
	}
</script>
